.TH "_binson_error" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_binson_error \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbinson_error_rec\fP \fBring\fP [\fBERROR_RING_SIZE\fP]"
.br
.ti -1c
.RI "uint8_t \fBhead\fP"
.br
.ti -1c
.RI "uint8_t \fBtail\fP"
.br
.ti -1c
.RI "\fBbinson_io\fP * \fBio\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Error handling context 
.SH "Field Documentation"
.PP 
.SS "\fBbinson_error_rec\fP ring[\fBERROR_RING_SIZE\fP]"
circular queue buffer 

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
