.TH "_binson_node_val_t" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_binson_node_val_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBv_data\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "binson_node_val_composite_t \fBchildren\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBb_data\fP"
.br
.ti -1c
.RI "int64_t \fBi_data\fP"
.br
.ti -1c
.RI "double \fBd_data\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
