.TH "_binson_io_strbuf_struct_t" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_binson_io_strbuf_struct_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBptr\fP"
.br
.ti -1c
.RI "size_t \fBbuf_size\fP"
.br
.ti -1c
.RI "size_t \fBcursor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
< String buffer access struct 

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
