.TH "_binson_node_val_t::v_data" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_binson_node_val_t::v_data \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t * \fBptr\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
