.TH "/home/kotomysha/binson/binson/src Directory Reference" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kotomysha/binson/binson/src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbinson\&.c\fP"
.br
.ti -1c
.RI "file \fBbinson\&.h\fP"
.br
.RI "\fIBinson-c library public API implementation file\&. \fP"
.ti -1c
.RI "file \fBbinson_config\&.h\fP"
.br
.RI "\fIbinson-c library build configuration file \fP"
.ti -1c
.RI "file \fBbinson_error\&.c\fP"
.br
.ti -1c
.RI "file \fBbinson_error\&.h\fP"
.br
.RI "\fIBinson error handling implementation\&. \fP"
.ti -1c
.RI "file \fBbinson_io\&.c\fP"
.br
.ti -1c
.RI "file \fBbinson_io\&.h\fP"
.br
.RI "\fIBinson input/output abstraction layer implementation\&. \fP"
.ti -1c
.RI "file \fBbinson_parser\&.c\fP"
.br
.RI "\fIBinson binary format parsing API implementation file\&. \fP"
.ti -1c
.RI "file \fBbinson_parser\&.h\fP"
.br
.RI "\fIBinson binary format parsing API header file\&. \fP"
.ti -1c
.RI "file \fBbinson_strstack\&.c\fP"
.br
.ti -1c
.RI "file \fBbinson_strstack\&.h\fP"
.br
.RI "\fIString stack implementation\&. \fP"
.ti -1c
.RI "file \fBbinson_utf8\&.c\fP"
.br
.ti -1c
.RI "file \fBbinson_utf8\&.h\fP"
.br
.RI "\fIUTF-8 utility functions implementation\&. \fP"
.ti -1c
.RI "file \fBbinson_util\&.c\fP"
.br
.RI "\fIUtility functions implementation\&. \fP"
.ti -1c
.RI "file \fBbinson_util\&.h\fP"
.br
.RI "\fIUtility functions header file\&. \fP"
.ti -1c
.RI "file \fBbinson_writer\&.c\fP"
.br
.RI "\fIBinson format writer implementation file\&. \fP"
.ti -1c
.RI "file \fBbinson_writer\&.h\fP"
.br
.RI "\fIBinson format writer API header file\&. \fP"
.in -1c
