.TH "binson_error_rec_" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binson_error_rec_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBcode\fP"
.br
.ti -1c
.RI "char * \fBcode_str\fP"
.br
.ti -1c
.RI "unsigned int \fBline\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.ti -1c
.RI "char * \fBdata\fP"
.br
.ti -1c
.RI "size_t \fBdata_len\fP"
.br
.ti -1c
.RI "binson_error_rec_flag \fBflag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Single error record structure 
.SH "Field Documentation"
.PP 
.SS "char* code_str"
Optional\&. If not NULL, point to detailed code description 

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
