.TH "/home/kotomysha/binson/binson/src/binson_parser.c" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/kotomysha/binson/binson/src/binson_parser.c \- 
.PP
Binson binary format parsing API implementation file\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'binson_parser\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Binson binary format parsing API implementation file\&. 


.PP
\fBAuthor:\fP
.RS 4
Alexander Reshniuk 
.RE
.PP
\fBDate:\fP
.RS 4
20/11/2015 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
