.TH "binson_io_" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binson_io_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbinson_io_type_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBbinson_io_mode_t\fP \fBmode\fP"
.br
.ti -1c
.RI "\fBbinson_io_struct_t\fP \fBhandle\fP"
.br
.ti -1c
.RI "\fBbinson_res\fP \fBstatus\fP"
.br
.ti -1c
.RI "int \fBerrno\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int errno"
Last errno value for this object 
.SS "\fBbinson_res\fP status"
Last input/output operation result 

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
