.TH "binson_" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binson_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbinson_node_t\fP * \fBroot\fP"
.br
.ti -1c
.RI "\fBbinson_writer\fP * \fBwriter\fP"
.br
.ti -1c
.RI "\fBbinson_writer\fP * \fBparser\fP"
.br
.ti -1c
.RI "\fBbinson_strstack_t\fP \fBstr_stack\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
