.TH "binson_traverse_cb_status_" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
binson_traverse_cb_status_ \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBbinson\fP * \fBobj\fP"
.br
.ti -1c
.RI "binson_node * \fBroot_node\fP"
.br
.ti -1c
.RI "\fBbinson_traverse_method\fP \fBt_method\fP"
.br
.ti -1c
.RI "binson_depth_t \fBmax_depth\fP"
.br
.ti -1c
.RI "binson_traverse_callback_t \fBcb\fP"
.br
.ti -1c
.RI "void * \fBparam\fP"
.br
.ti -1c
.RI "binson_node * \fBcurrent_node\fP"
.br
.ti -1c
.RI "\fBbinson_traverse_dir\fP \fBdir\fP"
.br
.ti -1c
.RI "binson_child_num_t \fBchild_num\fP"
.br
.ti -1c
.RI "binson_depth_t \fBdepth\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBdone\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for binson-c from the source code\&.
