.TH "todo" 3 "Tue Dec 1 2015" "binson-c" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBGlobal \fBbinson_io_vprintf\fP (binson_io *obj, const char *format, va_list args)\fP" 1c
Implement strict overflow checks to mimic nonportable vsnprintf()  
.IP "\fBGlobal \fBbinson_writer_write_integer\fP (binson_writer *writer, int64_t val)\fP" 1c
fix printing int64_t in C89 
.PP

